// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA63ije0a7LzEKybwulN2h1tMl5TDCu6V0',
    appId: '1:304703411541:web:4c93e8dde51ce2418b0bdc',
    messagingSenderId: '304703411541',
    projectId: 'tour-2d9f4',
    authDomain: 'tour-2d9f4.firebaseapp.com',
    storageBucket: 'tour-2d9f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjy0NFSP0ZajR701W2nk_ojTY2xhk3nmw',
    appId: '1:304703411541:android:ab3b7b6c1356081a8b0bdc',
    messagingSenderId: '304703411541',
    projectId: 'tour-2d9f4',
    storageBucket: 'tour-2d9f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1CrmxJK0JpE7NWo8aLfwAdUYT0vq4Zr0',
    appId: '1:304703411541:ios:c38aa53b4f44966b8b0bdc',
    messagingSenderId: '304703411541',
    projectId: 'tour-2d9f4',
    storageBucket: 'tour-2d9f4.appspot.com',
    iosClientId: '304703411541-a0fejuba1kl8mu1ot1jiag4oi1cf8sj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fortour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1CrmxJK0JpE7NWo8aLfwAdUYT0vq4Zr0',
    appId: '1:304703411541:ios:c38aa53b4f44966b8b0bdc',
    messagingSenderId: '304703411541',
    projectId: 'tour-2d9f4',
    storageBucket: 'tour-2d9f4.appspot.com',
    iosClientId: '304703411541-a0fejuba1kl8mu1ot1jiag4oi1cf8sj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fortour',
  );
}
